In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import make_classification

In [2]:
X,y=make_classification(n_samples=1000,# 1000 observations 
                        n_features=3,# total 3 features
                        n_redundant=1,
                        n_classes=2, # binary target/label
                        random_state=999)
                        

In [3]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [7]:
y[1:50]

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')

In [17]:
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [18]:
y_pred=classifier.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,classification_report

In [20]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.906060606060606
[[158  11]
 [ 20 141]]
0.9276315789473685
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       169
           1       0.93      0.88      0.90       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [21]:
from sklearn.model_selection import GridSearchCV

In [22]:
parameters={
    'n_neighbors':[1,2,3,4,5,6,7,8,9,10],
    'weights':['uniform', 'distance'],
    'algorithm':['ball_tree', 'kd_tree'],
    'p':[1,2]
}


In [23]:
cv=GridSearchCV(classifier,param_grid=parameters,verbose=3,refit=True)

In [24]:
cv.fit(X_train,y_train)

Fitting 5 folds for each of 80 candidates, totalling 400 fits
[CV 1/5] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform;, score=0.881 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform;, score=0.896 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform;, score=0.881 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform;, score=0.881 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform;, score=0.881 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance;, score=0.881 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance;, score=0.896 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance;, score=0.881 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance;, score=0.881 total time=   0.0s
[CV 5/5

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             verbose=3)

In [25]:
y_pred_new=cv.predict(X_test)

In [26]:
cv.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 9, 'p': 2, 'weights': 'uniform'}

In [27]:
classifier1=KNeighborsClassifier(algorithm='ball_tree',n_neighbors=9,p=2,weights='uniform')

In [29]:
classifier1.fit(X_train,y_train)

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=9)

In [30]:
y_pred_best=classifier1.predict(X_test)

In [31]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.906060606060606
[[158  11]
 [ 20 141]]
0.9276315789473685
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       169
           1       0.93      0.88      0.90       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [32]:
from sklearn.neighbors import KNeighborsRegressor

In [33]:
X,y=make_classification(n_samples=1000,n_features=3,n_redundant=1,n_classes=2,random_state=999)

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [43]:
regressor=KNeighborsRegressor(n_neighbors=2,algorithm='auto')

In [44]:
regressor.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=2)

In [45]:
y_pred=regressor.predict(X_test)

In [46]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))


0.6149252085706935
0.12575757575757576
0.09621212121212121
