In [3]:
import pandas as pd
import numpy as np


In [11]:
## Nominal values 
df=pd.DataFrame({'color':['red','blue','green','green','red']})

In [3]:
df

color
0    red
1   blue
2  green
3  green
4    red

In [4]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [6]:
lbl_encoder.fit_transform(df[['color']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2])

In [7]:
lbl_encoder.transform([['red']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [8]:
lbl_encoder.transform([['blue']])

array([0])

In [9]:
lbl_encoder.transform([['green']])

array([1])

In [10]:
## ordinal encoding is used for ranks 

## Ordinal Encoding 

In [5]:
from sklearn.preprocessing import OrdinalEncoder

In [14]:
df1=pd.DataFrame({'size':['small','medium','large','medium','small','large']})

In [15]:
df1

size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [17]:
## Ranking we create an instance for ordinal encoder and perform fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [19]:
encoder.fit_transform(df1[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [20]:
encoder.transform([['small']])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

## Target Guided Ordinal Encoding
Its is a tecgbicque used to encode categorical varoiable based on their relationship with the target variable .


In [6]:
df1=pd.DataFrame({'city':['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]})

In [7]:
df1

city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [11]:
mean_price=df1.groupby('city')['price'].mean().to_dict()

In [12]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [15]:
df1['city_encoded']=df1['city'].map(mean_price)

In [17]:
df1[['price','city_encoded']]

price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [19]:
import seaborn as sns 
df2=sns.load_dataset('tips')

In [20]:
df2

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [21]:
mean_tips=df2.groupby('time')['total_bill'].mean().to_dict()

In [22]:
mean_tips

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [26]:
df2['mean_total_bill']=df2['time'].map(mean_tips)

In [27]:
df2

total_bill   tip     sex smoker   day    time  size mean_total_bill
0         16.99  1.01  Female     No   Sun  Dinner     2       20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3       20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3       20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2       20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4       20.797159
..          ...   ...     ...    ...   ...     ...   ...             ...
239       29.03  5.92    Male     No   Sat  Dinner     3       20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2       20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2       20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2       20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2       20.797159

[244 rows x 8 columns]

In [28]:
df2[['total_bill','mean_total_bill']]

total_bill mean_total_bill
0         16.99       20.797159
1         10.34       20.797159
2         21.01       20.797159
3         23.68       20.797159
4         24.59       20.797159
..          ...             ...
239       29.03       20.797159
240       27.18       20.797159
241       22.67       20.797159
242       17.82       20.797159
243       18.78       20.797159

[244 rows x 2 columns]