## Numpy is numerical python 


In [42]:
import numpy as np

In [44]:
l=[1,2,3,4,5]

In [43]:
arr=np.array(l)

In [45]:
arr

array([1, 2, 3, 4, 5])

In [46]:
type(arr)

numpy.ndarray

In [19]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [22]:
arr1=np.array([[1,2,3],[2,3,4]])

In [23]:
arr.ndim

1

In [24]:
arr1.ndim

2

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [47]:
mat=np.matrix(l)

In [33]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [34]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [35]:
a=arr

In [36]:
arr

array([1, 2, 3, 4, 5])

In [37]:
a

array([1, 2, 3, 4, 5])

In [48]:
arr[0]=100

In [49]:
arr

array([100,   2,   3,   4,   5])

In [50]:
a

array([100,   2,   3,   4,   5])

## swallow operation done above

In [41]:
b=np.copy(arr)

In [52]:
b[0]=234

In [53]:
b

array([234,   2,   3,   4,   5])

In [54]:
arr

array([100,   2,   3,   4,   5])

In [55]:
a

array([100,   2,   3,   4,   5])

## deep copy is done of b as there will be no changes done on a and arr

## functions in array 

In [56]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [57]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

## matrix of 0,1,2 on x and 0,1,2, on y axis is made and is compared for equal to and multiplication matrix 

In [58]:
list(i *i for i in range(5))

[0, 1, 4, 9, 16]

In [59]:
iterable =(i *i for i in range(5))

In [60]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [61]:
np.fromstring('23 45 56',sep=' ')

array([23., 45., 56.])

In [64]:
np.fromstring('23,45,6',sep=',')

array([23., 45.,  6.])

In [65]:
arr

array([100,   2,   3,   4,   5])

In [66]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [68]:
arr.ndim
## demension is collected from ndim

1

In [69]:
arr1.ndim

2

In [70]:
arr.size

5

In [71]:
arr1.size

6

In [72]:
arr.shape

(5,)

In [73]:
arr1.shape

(2, 3)

In [74]:
arr.dtype

dtype('int64')

In [75]:
arr1.dtype

dtype('int64')

## numpy functionality 

In [1]:
import numpy as np

In [2]:
range(5)

range(0, 5)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.5,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [8]:
list(np.arange(.4,10.4))

[0.4,
 1.4,
 2.4,
 3.3999999999999995,
 4.3999999999999995,
 5.3999999999999995,
 6.3999999999999995,
 7.3999999999999995,
 8.399999999999999,
 9.399999999999999]

In [9]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
arr =np.ones((3,4))

In [20]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [22]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [24]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [26]:
arr1=np.eye(5)

In [27]:
import pandas as pd

In [28]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [29]:
np.random.rand(2,3)

array([[0.46941916, 0.77375858, 0.53796513],
       [0.34938231, 0.60748551, 0.15939341]])

In [30]:
np.random.randn(2,3)

array([[ 0.98072783, -0.15099126,  1.07360667],
       [-0.39255626, -0.10735255,  0.37528346]])

In [34]:
arr2=np.random.randint(1,5,(3,4))

In [35]:
arr2

array([[3, 3, 2, 2],
       [2, 4, 4, 2],
       [2, 4, 1, 4]])

In [36]:
arr2.size

12

In [37]:
arr2.shape

(3, 4)

In [38]:
arr2.reshape(6,2)

array([[3, 3],
       [2, 2],
       [2, 4],
       [4, 2],
       [2, 4],
       [1, 4]])

In [39]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

## new shape should be a multiplier of the total no of data set size we already have in matrices 

In [40]:
arr2.reshape(2,6)

array([[3, 3, 2, 2, 2, 4],
       [4, 2, 2, 4, 1, 4]])

In [41]:
arr2.reshape(4,-1)

array([[3, 3, 2],
       [2, 2, 4],
       [4, 2, 2],
       [4, 1, 4]])

In [ ]:
## any negative no wont affect the matrix 

In [44]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[3]]],


         [[[3]]],


         [[[2]]]],



        [[[[2]]],


         [[[2]]],


         [[[4]]]]],




       [[[[[4]]],


         [[[2]]],


         [[[2]]]],



        [[[[4]]],


         [[[1]]],


         [[[4]]]]]])

In [45]:
arr1=np.random.randint(1,10,(5,6))

In [46]:
arr1

array([[9, 5, 2, 3, 4, 1],
       [7, 2, 7, 7, 6, 4],
       [3, 5, 2, 7, 1, 2],
       [6, 6, 9, 7, 2, 7],
       [5, 7, 5, 3, 8, 3]])

In [47]:
arr1>8

array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False]])

In [48]:
arr1[arr1>8]

array([9, 9])

In [50]:
arr1[0,[0,1]]

array([9, 5])

In [54]:
arr1[2:4]

array([[3, 5, 2, 7, 1, 2],
       [6, 6, 9, 7, 2, 7]])

In [57]:
arr1[2:4,[2,3]]

array([[2, 7],
       [9, 7]])

In [59]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))


In [60]:
arr1

array([[1, 2, 1],
       [1, 1, 2],
       [1, 2, 2]])

In [61]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [2, 2, 2]])

In [62]:
arr1+arr2

array([[2, 3, 2],
       [2, 3, 3],
       [3, 4, 4]])

In [63]:
arr1-arr2

array([[ 0,  1,  0],
       [ 0, -1,  1],
       [-1,  0,  0]])

In [64]:
arr1*arr2

array([[1, 2, 1],
       [1, 2, 2],
       [2, 4, 4]])

In [65]:
## matrix multiplication 

arr1@arr2

array([[5, 7, 5],
       [6, 7, 6],
       [7, 9, 7]])

In [66]:
arr1/arr2

array([[1. , 2. , 1. ],
       [1. , 0.5, 2. ],
       [0.5, 1. , 1. ]])

In [67]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

## numpy - Broadcasting 


In [69]:
arr=np.zeros((3,4))

In [70]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [76]:
a=np.array([1,2,3,4])

In [77]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [80]:
b=np.array([[3,4,5]])

In [84]:
arr1=arr+b.T

In [82]:
b.T

array([[3],
       [4],
       [5]])

In [85]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [86]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [87]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [88]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [89]:
np.mean(arr1)

4.0

In [90]:
np.max(arr1)

5.0

In [91]:
np.min(arr1)

3.0

In [92]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [1]:
import numpy as np

## numpy- Array Manupulation

In [5]:
arr= np.random.randint(1,10,(4,4))

In [6]:
arr

array([[5, 8, 9, 6],
       [8, 2, 9, 8],
       [2, 5, 5, 1],
       [5, 5, 7, 4]])

In [7]:
arr.reshape(8,2)

array([[5, 8],
       [9, 6],
       [8, 2],
       [9, 8],
       [2, 5],
       [5, 1],
       [5, 5],
       [7, 4]])

In [8]:
arr.T

array([[5, 8, 2, 5],
       [8, 2, 5, 5],
       [9, 9, 5, 7],
       [6, 8, 1, 4]])

In [9]:
arr

array([[5, 8, 9, 6],
       [8, 2, 9, 8],
       [2, 5, 5, 1],
       [5, 5, 7, 4]])

In [10]:
arr.flatten()

array([5, 8, 9, 6, 8, 2, 9, 8, 2, 5, 5, 1, 5, 5, 7, 4])

In [11]:
arr

array([[5, 8, 9, 6],
       [8, 2, 9, 8],
       [2, 5, 5, 1],
       [5, 5, 7, 4]])

In [12]:
arr.flatten()

array([5, 8, 9, 6, 8, 2, 9, 8, 2, 5, 5, 1, 5, 5, 7, 4])

In [13]:
arr

array([[5, 8, 9, 6],
       [8, 2, 9, 8],
       [2, 5, 5, 1],
       [5, 5, 7, 4]])

In [15]:
np.expand_dims(arr,axis=1)

array([[[5, 8, 9, 6]],

       [[8, 2, 9, 8]],

       [[2, 5, 5, 1]],

       [[5, 5, 7, 4]]])

In [16]:
data=np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [20]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [23]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [26]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Numpy Binary Operation (addition , subtraction )

In [29]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [28]:
arr1

array([[2, 4, 5, 7],
       [3, 2, 1, 6],
       [8, 3, 3, 5]])

In [30]:
arr2

array([[5, 5, 3, 5],
       [8, 7, 9, 5],
       [3, 1, 7, 2]])

In [31]:
arr1+arr2

array([[14, 13, 11, 11],
       [15, 14, 12,  7],
       [ 6,  9, 14,  4]])

In [32]:
arr1*arr2

array([[45, 40, 24, 30],
       [56, 49, 27, 10],
       [ 9,  8, 49,  4]])

In [33]:
arr1/arr2

array([[1.8       , 1.6       , 2.66666667, 1.2       ],
       [0.875     , 1.        , 0.33333333, 0.4       ],
       [1.        , 8.        , 1.        , 1.        ]])

In [35]:
arr1-arr2

array([[ 4,  3,  5,  1],
       [-1,  0, -6, -3],
       [ 0,  7,  0,  0]])

In [36]:
arr1**arr2

array([[  59049,   32768,     512,    7776],
       [5764801,  823543,   19683,      32],
       [     27,       8,  823543,       4]])

In [37]:
~arr1

array([[-10,  -9,  -9,  -7],
       [ -8,  -8,  -4,  -3],
       [ -4,  -9,  -8,  -3]])

In [38]:
arr1

array([[9, 8, 8, 6],
       [7, 7, 3, 2],
       [3, 8, 7, 2]])

In [39]:
~arr2

array([[ -6,  -6,  -4,  -6],
       [ -9,  -8, -10,  -6],
       [ -4,  -2,  -8,  -3]])

In [40]:
arr2

array([[5, 5, 3, 5],
       [8, 7, 9, 5],
       [3, 1, 7, 2]])

In [41]:
arr1>arr2

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False,  True, False, False]])

## Numpy - String functions 

arr=np.array(['sudh','agarwal'])

In [44]:
arr

array(['sudh', 'agarwal'], dtype='<U7')

In [45]:
np.char.upper(arr)

array(['SUDH', 'AGARWAL'], dtype='<U7')

In [46]:
np.char.capitalize(arr)

array(['Sudh', 'Agarwal'], dtype='<U7')

In [47]:
np.char.title(arr)

array(['Sudh', 'Agarwal'], dtype='<U7')

## numpy-Mathematical functions

In [48]:
arr1

array([[9, 8, 8, 6],
       [7, 7, 3, 2],
       [3, 8, 7, 2]])

In [49]:
np.sin(arr1)

array([[ 0.41211849,  0.98935825,  0.98935825, -0.2794155 ],
       [ 0.6569866 ,  0.6569866 ,  0.14112001,  0.90929743],
       [ 0.14112001,  0.98935825,  0.6569866 ,  0.90929743]])

In [50]:
np.cos(arr1)

array([[-0.91113026, -0.14550003, -0.14550003,  0.96017029],
       [ 0.75390225,  0.75390225, -0.9899925 , -0.41614684],
       [-0.9899925 , -0.14550003,  0.75390225, -0.41614684]])

In [52]:
np.tan(arr1)

array([[-0.45231566, -6.79971146, -6.79971146, -0.29100619],
       [ 0.87144798,  0.87144798, -0.14254654, -2.18503986],
       [-0.14254654, -6.79971146,  0.87144798, -2.18503986]])

In [53]:
np.log10(arr1)

array([[0.95424251, 0.90308999, 0.90308999, 0.77815125],
       [0.84509804, 0.84509804, 0.47712125, 0.30103   ],
       [0.47712125, 0.90308999, 0.84509804, 0.30103   ]])

In [54]:
np.exp(arr1)

array([[8.10308393e+03, 2.98095799e+03, 2.98095799e+03, 4.03428793e+02],
       [1.09663316e+03, 1.09663316e+03, 2.00855369e+01, 7.38905610e+00],
       [2.00855369e+01, 2.98095799e+03, 1.09663316e+03, 7.38905610e+00]])

In [56]:
np.power(arr1,2)

array([[81, 64, 64, 36],
       [49, 49,  9,  4],
       [ 9, 64, 49,  4]])

In [57]:
np.mean(arr1)

5.833333333333333

In [58]:
np.median(arr1)

7.0

In [60]:
np.std(arr1)

2.4776781245530843

In [61]:
np.var(arr1)

6.13888888888889

In [62]:
np.min(arr1)

2

In [63]:
np.max(arr1)

9

## Numpy - Arithmatic Operations 

In [65]:
arr1

array([[9, 8, 8, 6],
       [7, 7, 3, 2],
       [3, 8, 7, 2]])

In [66]:
arr2

array([[5, 5, 3, 5],
       [8, 7, 9, 5],
       [3, 1, 7, 2]])

In [67]:
np.random.randint(1,10,(3,4))

array([[7, 8, 5, 2],
       [4, 8, 4, 2],
       [8, 7, 7, 6]])

In [68]:
arr1-arr2

array([[ 4,  3,  5,  1],
       [-1,  0, -6, -3],
       [ 0,  7,  0,  0]])

In [69]:
np.subtract(arr1,arr2)

array([[ 4,  3,  5,  1],
       [-1,  0, -6, -3],
       [ 0,  7,  0,  0]])

In [70]:
np.multiply(arr1,arr2)

array([[45, 40, 24, 30],
       [56, 49, 27, 10],
       [ 9,  8, 49,  4]])

In [72]:
np.mod(arr1,arr2)

array([[4, 3, 2, 1],
       [7, 0, 3, 2],
       [0, 0, 0, 0]])

In [73]:
np.power(arr1,arr2)

array([[  59049,   32768,     512,    7776],
       [5764801,  823543,   19683,      32],
       [     27,       8,  823543,       4]])

In [75]:
np.sqrt(arr1)

array([[3.        , 2.82842712, 2.82842712, 2.44948974],
       [2.64575131, 2.64575131, 1.73205081, 1.41421356],
       [1.73205081, 2.82842712, 2.64575131, 1.41421356]])

In [81]:
## sort, search and counting function 

In [82]:
import numpy as np

In [89]:
arr=np.array([9, 8, 8, 6, 7, 7, 3, 2, 3, 8, 7, 2])

In [90]:
arr

array([9, 8, 8, 6, 7, 7, 3, 2, 3, 8, 7, 2])

In [91]:
np.sort(arr)

array([2, 2, 3, 3, 6, 7, 7, 7, 8, 8, 8, 9])

In [87]:
arr1

array([[9, 8, 8, 6],
       [7, 7, 3, 2],
       [3, 8, 7, 2]])

In [88]:
arr1.flatten()

array([9, 8, 8, 6, 7, 7, 3, 2, 3, 8, 7, 2])

In [93]:
np.searchsorted(arr,10)

12

In [107]:
arr1=np.array([0,544,54,4435,467,7,0,0,0,0])

In [108]:
np.count_nonzero(arr1)

5

In [109]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5]),)

In [111]:
np.extract(arr>2,arr)

array([9, 8, 8, 6, 7, 7, 3, 3, 8, 7])

In [ ]:
## Numpy - Biteswapping

In [114]:
arr.byteswap(True)

array([648518346341351424, 576460752303423488, 576460752303423488,
       432345564227567616, 504403158265495552, 504403158265495552,
       216172782113783808, 144115188075855872, 216172782113783808,
       576460752303423488, 504403158265495552, 144115188075855872])

In [113]:
arr

array([9, 8, 8, 6, 7, 7, 3, 2, 3, 8, 7, 2])

In [115]:
arr

array([648518346341351424, 576460752303423488, 576460752303423488,
       432345564227567616, 504403158265495552, 504403158265495552,
       216172782113783808, 144115188075855872, 216172782113783808,
       576460752303423488, 504403158265495552, 144115188075855872])

In [ ]:
## numpy Copies and Views

In [116]:
arr1

array([   0,  544,   54, 4435,  467,    7,    0,    0,    0,    0])

In [117]:
a=np.copy(arr1)

In [118]:
a

array([   0,  544,   54, 4435,  467,    7,    0,    0,    0,    0])

In [120]:
b=arr1.view()

In [121]:
b

array([   0,  544,   54, 4435,  467,    7,    0,    0,    0,    0])

In [123]:
import numpy.matlib as nm

In [124]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [125]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [127]:
nm.eye((4))

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Numpy Linear algebra 

In [128]:
arr1

array([   0,  544,   54, 4435,  467,    7,    0,    0,    0,    0])

In [129]:
arr2

array([[5, 5, 3, 5],
       [8, 7, 9, 5],
       [3, 1, 7, 2]])

In [132]:
arr1=np.random.randint([[2,3],[4,5]])
arr2=np.random.randint([[5,3],[2,5]])

In [133]:
arr1

array([[0, 1],
       [1, 3]])

In [134]:
arr2

array([[2, 1],
       [1, 2]])

In [135]:
np.dot(arr1,arr2)

array([[1, 2],
       [5, 7]])

In [136]:
arr1@arr2

array([[1, 2],
       [5, 7]])