In [1]:
import numpy as np

In [18]:
list_1 = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_1)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
var_list=[1,2,3,4,5]

In [6]:
type(var_list)

list

In [7]:
type(array_list)

numpy.ndarray

In [8]:
var_list

[1, 2, 3, 4, 5]

In [10]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
## there is a difference b/w list and array list as var list as in array list everything is stored 
##inside a tuple in a list or martix or array form while in list it is stored in normal manner without having mathmetical 
## inplimentations to it

In [27]:
array_list = np.array(object = list_1, dtype = int)

In [28]:
array_list

array([1, 2, 3, 4, 5])

In [29]:
array_list.dtype
                     

dtype('int64')

In [ ]:
## Ans 3.
##yes there is a diff. as said earlier int64 is a type of array where it is stored in a tuple way 

In [32]:
num_array=np.random.randint(1,10,(3,4))

In [33]:
 num_array

array([[3, 3, 9, 1],
       [3, 8, 9, 8],
       [9, 5, 5, 1]])

In [34]:
## Ans 4 
num_array.shape

(3, 4)

In [37]:
num_array.size

12

In [57]:
np.fromfunction(lambda i,j: i*j,(1,2))

array([[0., 0.]])

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.fromfunction(lambda x:x in x print x== np.eye(5,5))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3826201145.py, line 1)