In [ ]:
## Ans 1: w.x+b=0 where w is a vector normal to hyperplane and b is an offset. If the value of w.x+b>0 then we can say it is a positive point otherwise it is a negative point

In [ ]:
## Ans 2: objective is to find the hyperplane marginal lines or converting 2d-3d or 1d to 3d with mathmatical formulaes for distinctly seperable points in dataset
## to find a function f(x) that deviates from yn by a value no greater than ε for each training point x, and at the same time is as flat as possible.

In [ ]:
## Ans 3: a simple method where a Non Linear data is projected onto a higher dimension space so as to make it easier to classify the data where it could be linearly divided by a plane

In [ ]:
## Ans 4: upport vectors are data points that are closer to the hyperplane and influence the position and orientation of the hyperplane. Using these support vectors, we maximize the margin of the classifier. Deleting the support vectors will change the position of the hyperplane. These are the points that help us build our SVM.
## example survey done for 4wheeler owner for brands maruti,toyota , if the data is trained to predict the best outcome and if the support vector position changes the vector magnitiude differs 

In [ ]:
## Ans 5 :  a point is a hyperplane in 1-dimensional space, a line is a hyperplane in 2-dimensional space, and a plane is a hyperplane in 3-dimensional space

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [5]:
dataset.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [10]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [11]:
dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [15]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [23]:
## No null values are preent in the dataset 
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [24]:
## all values are in int and float type 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [25]:
df['target']=dataset.target

In [26]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [27]:
## Now we have our feature names and target in dataset we will do the train split for independentb and dependent features
df['target'].unique()

array([0, 1, 2])

In [47]:
## we will only train for 0 and 1 
from sklearn.model_selection import train_test_split
X=df.iloc[:,:-1]

In [31]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [34]:
df[df['target']!=2]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [35]:
df_copy=df[df['target']!=2]

In [49]:
X=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [41]:
y.unique(),y

(array([0, 1]),
 0     0
 1     0
 2     0
 3     0
 4     0
      ..
 95    1
 96    1
 97    1
 98    1
 99    1
 Name: target, Length: 100, dtype: int64)

In [50]:
## Now train model for X and y 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [51]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
55                5.7               2.8                4.5               1.3
88                5.6               3.0                4.1               1.3
26                5.0               3.4                1.6               0.4
42                4.4               3.2                1.3               0.2
69                5.6               2.5                3.9               1.1
..                ...               ...                ...               ...
60                5.0               2.0                3.5               1.0
71                6.1               2.8                4.0               1.3
14                5.8               4.0                1.2               0.2
92                5.8               2.6                4.0               1.2
51                6.4               3.2                4.5               1.5

[80 rows x 4 columns]

In [53]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int64

In [61]:
from sklearn.svm import SVC

In [62]:
svc=SVC(kernel='linear')

In [63]:
svc

SVC(kernel='linear')

In [64]:
svc.fit(X_train,y_train)

SVC(kernel='linear')

In [65]:
y_pred=svc.predict(X_test)

In [66]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [67]:
svc.coef_

array([[ 0.04639127, -0.52086366,  1.00297397,  0.46410058]])

In [68]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [69]:
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

1.0
[[12  0]
 [ 0  8]]


In [70]:
### Accuracy seems to be very high as 100 per 
## we will see for hypertuning the model with parameters 
from sklearn.model_selection import GridSearchCV

In [71]:
parameter={'C':[1,10,100,1000],
           'kernel':['linear'],
           'gamma':[0.1,0.11,0.001,0.111,0.0001]
           
          }

In [72]:
classifier=GridSearchCV(svc,param_grid=parameter,refit=True,cv=5,verbose=3)

In [73]:
classifier.fit(X_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END .....C=1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.11, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.11, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.11, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.11, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.11, kernel=linear;, score=1.000 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.001, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.001, kernel=linear

GridSearchCV(cv=5, estimator=SVC(kernel='linear'),
             param_grid={'C': [1, 10, 100, 1000],
                         'gamma': [0.1, 0.11, 0.001, 0.111, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [74]:
y_pred=classifier.predict(X_test)

In [75]:
classifier.best_params_

{'C': 1, 'gamma': 0.1, 'kernel': 'linear'}

In [76]:
new_svc=SVC(C=1,gamma=0.1,kernel='linear')

In [77]:
new_svc

SVC(C=1, gamma=0.1, kernel='linear')

In [79]:
new_svc.fit(X_train,y_train)

SVC(C=1, gamma=0.1, kernel='linear')

In [80]:
y_pred_new=new_svc.predict(X_test)

In [81]:
print(classification_report(y_test,y_pred_new))
print(accuracy_score(y_test,y_pred_new))
print(confusion_matrix(y_test,y_pred_new))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

1.0
[[12  0]
 [ 0  8]]
